services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: admin
      MB_DB_PASS: password
      MB_DB_HOST: postgres-metabase
      JAVA_OPTS: "-Xmx1g"
    deploy:
      resources:
        limits:
          memory: 1.5g
    networks:
      - docker_default
      - metabase-net
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    depends_on:
      postgres-metabase:
        condition: service_healthy
  postgres-metabase:
    image: postgres:latest
    container_name: postgres-metabase
    hostname: postgres
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: password
    networks:
      - metabase-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d metabaseappdb"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  docker_default:
    external: true
  metabase-net:
    driver: bridge
