services:
  trino-coordinator:  
    image: trinodb/trino:476
    container_name: trino-coordinator
    ports:  
      - "8080:8080"
    ulimits:
      nofile: 65536
    volumes:
      - ../trino_config/coordinator/config.properties:/etc/trino/config.properties
      - ../trino_config/catalog:/etc/trino/catalog
      - ../trino_config/coordinator/init.sql:/etc/trino/init.sql
    env_file:
      - ../.env
  trino-worker-1:  
    image: trinodb/trino:476
    container_name: trino-worker-1  
    ulimits:
      nofile: 65536
    volumes:
      - ../trino_config/worker/config.properties:/etc/trino/config.properties
      - ../trino_config/catalog:/etc/trino/catalog
    env_file:
      - ../.env 
    depends_on:
      - trino-coordinator

  trino-worker-2:  
    image: trinodb/trino:476
    container_name: trino-worker-2  
    ulimits:
      nofile: 65536
    volumes:
      - ../trino_config/worker/config.properties:/etc/trino/config.properties
      - ../trino_config/catalog:/etc/trino/catalog
    env_file:
      - ../.env  
    depends_on:
      - trino-coordinator

